### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by roberto-arista** [typemytype/extensionBundle#1]
- [x] remove `AppKit` dependency
- [x] handle other dependencies from RF app
- [x] switch paths to `pathlib.Path`
- [x] type annotations
- [x] github action
- [x] unit tests?
